language: node_js
node_js:
  - 14

before_script:
  - echo MODE=production > .env
  - echo PROD_API=${PROD_API} > .env

script: npm run build

deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist
  cleanup: false
  on:
    all_branches: true