export default {
  SET_WORKOUTS: 'SET_WORKOUTS',
  SET_PERIOD: 'SET_PERIOD',
  
  FETCH_WORKOUTS_START: 'FETCH_WORKOUTS_START',
  FETCH_WORKOUTS_SUCCESS: 'FETCH_WORKOUTS_SUCCESS',
  FETCH_WORKOUTS_FAILURE: 'FETCH_WORKOUTS_FAILURE',
};
